language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
    - composer install -o

script: ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
